version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init/sql:/docker-entrypoint-initdb.d
      - ./db-init/csv:/docker-entrypoint-initdb.d/csv
    ports:
      - "5433:5432"
volumes:
  postgres_data: